const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const fmt = n => new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(n);
async function load(){
  const [metrics, tree, defaults, pred] = await Promise.all([
    fetch('artifacts/metrics.json').then(r=>r.json()), fetch('artifacts/tree.json').then(r=>r.json()), fetch('artifacts/defaults.json').then(r=>r.json()), fetch('artifacts/test_predictions.csv').then(r=>r.text())
  ]);
  renderMeta(metrics); renderMetrics(metrics); renderPredictions(pred); renderForm(metrics,defaults,tree);
}
function renderMeta(m){const items=[['Nguồn dữ liệu',`${m.source_rows} dòng · ${m.source_columns} cột`],['Chia dữ liệu',`Train ${m.train_rows} · Test ${m.test_rows}`],['Cấu hình cây',`depth ${m.max_depth} · ${m.leaf_count} lá`],['Random seed',m.seed]];document.querySelector('#run-meta').innerHTML=items.map(x=>`<div class="meta"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}
function renderMetrics(m){const a=[['Train MAE',money(m.train.MAE)],['Test MAE',money(m.test.MAE)],['Train RMSE',money(m.train.RMSE)],['Test RMSE',money(m.test.RMSE)],['Train R²',m.train.R2],['Test R²',m.test.R2]];document.querySelector('#metric-cards').innerHTML=a.map(x=>`<div class="metric"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('')}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);return lines.slice(1).map(x=>{const [actual,predicted,error,absolute_error]=x.split(',').map(Number);return {actual,predicted,absolute_error}})}
function renderPredictions(text){document.querySelector('#pred-table tbody').innerHTML=parseCSV(text).slice(0,25).map((r,i)=>`<tr><td>${i+1}</td><td>${money(r.actual)}</td><td>${money(r.predicted)}</td><td>${money(r.absolute_error)}</td></tr>`).join('')}
function renderForm(m, defaults, tree){const labels=m.feature_labels;const form=document.querySelector('#predict-form');form.innerHTML=m.features.map(f=>`<div class="field"><label for="${f}">${labels[f]}</label><input id="${f}" type="number" step="any" value="${Math.round(defaults[f]*100)/100}" required /></div>`).join('')+'<button type="submit">Dự đoán và duyệt node cây</button>';form.addEventListener('submit',e=>{e.preventDefault();const x=Object.fromEntries(m.features.map(f=>[f,Number(document.getElementById(f).value)]));const path=[];let n=tree;while(!n.leaf){const goLeft=x[n.feature]<=n.threshold;path.push({text:`${labels[n.feature]} ${goLeft?'≤':'>'} ${fmt(n.threshold)} → nhánh ${goLeft?'trái':'phải'}`,node:n});n=goLeft?n.left:n.right}path.push({text:`Nút lá #${n.id}: trung bình ${money(n.value)} từ ${n.samples} mẫu`,node:n,leaf:true});document.querySelector('#prediction-value').textContent=money(n.value);document.querySelector('#path-text').textContent=`Đã đi qua ${path.length-1} điều kiện và dừng tại nút lá.`;document.querySelector('#path-nodes').innerHTML=path.map(p=>`<div class="node ${p.leaf?'leaf':''}">${p.text}</div>`).join('')})}
load().catch(e=>{document.body.insertAdjacentHTML('beforeend',`<p style="padding:20px;color:red">Không tải được artifacts: ${e}</p>`)})
